# Generated by Django 4.1.5 on 2023-01-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('social_media_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
                ('pushed_at', models.CharField(max_length=50)),
                ('stars', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('repo_url', models.CharField(max_length=100)),
                ('issues', models.IntegerField()),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroapi.profile')),
            ],
        ),
    ]
