# Generated by Django 4.1.5 on 2023-01-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositories',
            name='username',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Repositories',
        ),
    ]
