# Generated by Django 4.1.5 on 2023-01-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroapi', '0004_delete_repository_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
